In [1]:
import numpy as np
from env import State, OneStepEnv
from Agent import Single_State_Agent

In [2]:
team_structure = (2,1,1)

p0 = np.array([[0,0], [0], [2]])
e0 = np.array([[2,2], [3], [0]])

S = State(p0, e0)
env = OneStepEnv(S)

A = Single_State_Agent(S, env)
#a = A.select_action(1.)
a = [2, 2, 3, 0]

print(a)

s, r, _, _ = env.step(a)

[2, 2, 3, 0]


/var/folders/5n/lj6nx7xj3mx2yb3sk947mnlc0000gn/T/ipykernel_4512/650627497.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  p0 = np.array([[0,0], [0], [2]])
/var/folders/5n/lj6nx7xj3mx2yb3sk947mnlc0000gn/T/ipykernel_4512/650627497.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  e0 = np.array([[2,2], [3], [0]])


In [3]:
print(r)
print(s.e)
print(s.p)

[0.33333333 0.33333333 0.33333333 0.        ]
[[1.0, 1.0], [1.0], [0.0]]
[[2.0, 2.0], [2.0], [2.0]]


In [4]:
A.train(num_episodes=100000)

Episode 0 - dQ: 0.5
[[[0.  0.  0.  0. ]
  [0.  0.  0.5 0. ]
  [0.  0.  0.  0.5]
  [0.  0.  0.  0. ]]]
Episode 1000 - dQ: 0.0
[[[0.  0.  0.  0. ]
  [0.  0.  1.  0.5]
  [0.  0.  0.  1. ]
  [0.  0.  0.  0. ]]]
Episode 2000 - dQ: 0.0
[[[0.  0.  0.  0.5]
  [0.  0.  0.  0. ]
  [0.  0.  0.  1. ]
  [1.  0.  0.  0. ]]]
Episode 3000 - dQ: 0.5
[[[0.  0.  1.  0.5]
  [0.  0.  0.  0. ]
  [0.  0.  0.  1. ]
  [0.5 0.  0.  0. ]]]
Episode 4000 - dQ: 1.0
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 1.]
  [1. 0. 0. 0.]]]
Episode 5000 - dQ: 0.3333333333333333
[[[0.         0.         1.         0.33333333]
  [0.         0.         1.         0.33333333]
  [0.         0.         0.         1.        ]
  [0.         0.         0.         0.        ]]]
Episode 6000 - dQ: 1.0
[[[0.  0.  0.  0. ]
  [0.  0.  0.  0. ]
  [0.  0.  1.  0.5]
  [1.  0.  0.  0. ]]]
Episode 7000 - dQ: 0.3333333333333333
[[[0.         0.         1.         0.33333333]
  [0.         0.         1.         0.33333333]
  [0.         0.       

In [5]:
A.Q

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]]])