In [1]:
import numpy as np
from env import State, OneStepEnv
from Agent import Single_State_Agent

In [2]:
def ablation_train(p0, e0):
    S = State(p0, e0)
    env = OneStepEnv(S)

    for alpha in [0.01, 0.1, 0.3, 0.5]:
        A = Single_State_Agent(S, env, alpha=alpha)

        A.train(num_episodes=200000, verbose=False)

        print(f"Agent with alpha={alpha} -- {A.Q}")
    # Do the initial beliefs madder?

    for initial_beliefs in [0, -1, 1, 5]:
        A = Single_State_Agent(S, env, alpha=0.1)

        A.train(num_episodes=200000, verbose=False)

        print(f"Agent with alpha={alpha} -- {A.Q}")

In [3]:
# 2b

p0 = np.array([[0], [0,0], [2]], dtype=object)
e0 = np.array([[3], [2,2], [0]], dtype=object)

ablation_train(p0, e0)

Agent with alpha=0.01 -- [[[0.00000000e+000 0.00000000e+000 4.39095343e-001 5.00000000e-001]
  [1.05861217e-001 9.99665913e-002 5.00000000e-001 3.25608760e-001]
  [7.51623033e-002 9.68374232e-002 2.37121674e-001 5.00000000e-001]
  [2.42092166e-322 0.00000000e+000 0.00000000e+000 0.00000000e+000]]]
Agent with alpha=0.1 -- [[[0.00000000e+000 0.00000000e+000 2.74193092e-001 5.00000000e-001]
  [1.68684298e-001 1.78652302e-001 3.17769523e-001 5.00000000e-001]
  [1.61466914e-001 1.42209152e-001 5.00000000e-001 3.96283233e-001]
  [1.97626258e-323 0.00000000e+000 0.00000000e+000 0.00000000e+000]]]
Agent with alpha=0.3 -- [[[0.00000000e+000 0.00000000e+000 3.09887952e-001 5.00000000e-001]
  [3.75654374e-002 1.02037100e-001 5.00000000e-001 3.95000000e-001]
  [3.04172320e-002 1.91252801e-002 5.00000000e-001 3.50000000e-001]
  [4.94065646e-324 0.00000000e+000 0.00000000e+000 0.00000000e+000]]]
Agent with alpha=0.5 -- [[[0.00000000e+000 0.00000000e+000 2.50000000e-001 5.00000000e-001]
  [2.44140625

In [4]:
# 2a

p0 = np.array([[0], [0], [2]], dtype=object)
e0 = np.array([[3], [2], [0]], dtype=object)


ablation_train(p0, e0)

Agent with alpha=0.01 -- [[[0.00000000e+000 0.00000000e+000 2.50506539e-001 5.00000000e-001]
  [0.00000000e+000 0.00000000e+000 5.00000000e-001 2.32021959e-001]
  [2.42092166e-322 0.00000000e+000 0.00000000e+000 0.00000000e+000]]]
Agent with alpha=0.1 -- [[[0.00000000e+000 0.00000000e+000 1.65568943e-001 5.00000000e-001]
  [0.00000000e+000 0.00000000e+000 5.00000000e-001 2.58059077e-001]
  [1.97626258e-323 0.00000000e+000 0.00000000e+000 0.00000000e+000]]]
Agent with alpha=0.3 -- [[[0.00000000e+000 0.00000000e+000 2.73700985e-001 5.00000000e-001]
  [0.00000000e+000 0.00000000e+000 5.00000000e-001 1.74947124e-001]
  [4.94065646e-324 0.00000000e+000 0.00000000e+000 0.00000000e+000]]]
Agent with alpha=0.5 -- [[[0.00000000e+000 0.00000000e+000 3.18017621e-002 5.00000000e-001]
  [0.00000000e+000 0.00000000e+000 5.00000000e-001 2.99103568e-002]
  [4.94065646e-324 0.00000000e+000 0.00000000e+000 0.00000000e+000]]]
Agent with alpha=0.5 -- [[[0.00000000e+000 0.00000000e+000 1.54056820e-001 5.00

In [5]:
# 1b

p0 = np.array([[0], [0], [2]], dtype=object)
e0 = np.array([[2], [2], [0]], dtype=object)

ablation_train(p0, e0)

Agent with alpha=0.01 -- [[[0.00000000e+000 0.00000000e+000 4.24691277e-223 4.25840725e-223]
  [0.00000000e+000 0.00000000e+000 4.97487437e-001 8.35382281e-002]
  [5.02512563e-001 0.00000000e+000 0.00000000e+000 0.00000000e+000]]]
Agent with alpha=0.1 -- [[[0.e+000 0.e+000 2.e-323 2.e-323]
  [0.e+000 0.e+000 2.e-323 2.e-323]
  [1.e+000 0.e+000 0.e+000 0.e+000]]]
Agent with alpha=0.3 -- [[[0.00000000e+000 0.00000000e+000 2.88235294e-001 3.33333333e-001]
  [0.00000000e+000 0.00000000e+000 2.96439388e-323 3.33333333e-001]
  [3.33333333e-001 0.00000000e+000 0.00000000e+000 0.00000000e+000]]]
Agent with alpha=0.5 -- [[[0.e+000 0.e+000 5.e-324 5.e-324]
  [0.e+000 0.e+000 5.e-324 5.e-324]
  [1.e+000 0.e+000 0.e+000 0.e+000]]]
Agent with alpha=0.5 -- [[[0.e+000 0.e+000 2.e-323 2.e-323]
  [0.e+000 0.e+000 2.e-323 2.e-323]
  [1.e+000 0.e+000 0.e+000 0.e+000]]]
Agent with alpha=0.5 -- [[[0.e+000 0.e+000 2.e-323 2.e-323]
  [0.e+000 0.e+000 2.e-323 2.e-323]
  [1.e+000 0.e+000 0.e+000 0.e+000]]]
Age

In [6]:
# 1c

p0 = np.array([[0], [0], [2]], dtype=object)
e0 = np.array([[2], [1], [0]], dtype=object)

ablation_train(p0, e0)

Agent with alpha=0.01 -- [[[0.  0.  0.  0.5]
  [0.  0.  0.  0. ]
  [0.5 0.  0.  0. ]]]
Agent with alpha=0.1 -- [[[0.  0.  0.  0.5]
  [0.  0.  0.  0. ]
  [0.5 0.  0.  0. ]]]
Agent with alpha=0.3 -- [[[0.  0.  0.  0.5]
  [0.  0.  0.  0. ]
  [0.5 0.  0.  0. ]]]
Agent with alpha=0.5 -- [[[0.  0.  0.  0.5]
  [0.  0.  0.  0. ]
  [0.5 0.  0.  0. ]]]
Agent with alpha=0.5 -- [[[0.  0.  0.  0.5]
  [0.  0.  0.  0. ]
  [0.5 0.  0.  0. ]]]
Agent with alpha=0.5 -- [[[0.  0.  0.  0.5]
  [0.  0.  0.  0. ]
  [0.5 0.  0.  0. ]]]
Agent with alpha=0.5 -- [[[0.  0.  0.  0.5]
  [0.  0.  0.  0. ]
  [0.5 0.  0.  0. ]]]
Agent with alpha=0.5 -- [[[0.  0.  0.  0.5]
  [0.  0.  0.  0. ]
  [0.5 0.  0.  0. ]]]
